dark_theme: true
autoload_model: true
max_new_tokens: 500
max_new_tokens_min: 1
max_new_tokens_max: 4096
auto_max_new_tokens: false
seed: -1
negative_prompt: ''
character: David
name1: Leon
name2: Assistant
context: This is a conversation with your Assistant. It is a computer program designed to help you with various tasks such as answering questions, providing recommendations, and helping with decision making. You can ask it anything you want and it will do its best to give you accurate and relevant information.
greeting: ''
turn_template: ''
custom_stopping_strings: ''
add_bos_token: true
ban_eos_token: false
skip_special_tokens: true
truncation_length: 2048
truncation_length_min: 0
truncation_length_max: 16384
mode: chat
start_with: ''
chat_style: TheEncrypted777
instruction_template: None
chat-instruct_command: |-
  Continue the chat dialogue below. Write a single reply for the character "<|character|>".

  <|prompt|>
default_extensions:
- gallery
preset: david_agent
prompt: QA
